version: "3"

services:
  preload:
    logging:
      driver: none
    container_name: graphdb-preload
    # image: ontotext/graphdb:${GRAPHDB_VERSION}-ee
    build:
      context: src/test/resources/graphdb-docker-master/free-edition
      dockerfile: Dockerfile
      args:
        version: ${GRAPHDB_VERSION}

    # Load single file from ./import in repo define in ./graphdb-repo-config.ttl
    entrypoint: [ "/opt/graphdb/dist/bin/preload", "-c", "/opt/graphdb/graphdb-repo-config.ttl", "/opt/graphdb/home/graphdb-import/test.trigs", "--force" ]

    environment:
      GDB_JAVA_OPTS: >-
        -Xmx${GRAPHDB_HEAP_SIZE} -Xms${GRAPHDB_HEAP_SIZE}
        -Dgraphdb.home=/opt/graphdb/home
        -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
        -Dgraphdb.workbench.cors.enable=true
        -Denable-context-index=true
        -Dentity-pool-implementation=transactional
        -Dhealth.max.query.time.seconds=60
        -Dgraphdb.append.request.id.headers=true
        -Dreuse.vars.in.subselects=true
    volumes:
      # Change folders in the .env file or directly here
      # host directory (local filesystem on linux): virtual directory
      # Mounts files from your local file system (left) to a "virtual" docker governed filesystem (right).
      # ${...} environment variables are defined in .env
      - ${REPOSITORY_CONFIG_FILE}:/opt/graphdb/graphdb-repo-config.ttl
      - ${GRAPHDB_HOME}:/opt/graphdb/home
      - ${IMPORT_FOLDER}:/opt/graphdb/home/graphdb-import
      - ${IMPORT_FILE}:/opt/graphdb/home/graphdb-import/test.trigs
  database:
    container_name: graphdb
    # image: ontotext/graphdb:9.3.0-ee
    build:
      context: src/test/resources/graphdb-docker-master/free-edition
      dockerfile: Dockerfile
      args:
        version: 9.10.3
    restart: unless-stopped
    environment: 
      GDB_JAVA_OPTS: >-
        -Xmx2g -Xms2g
        -Dgraphdb.home=/opt/graphdb/home
        -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
        -Dgraphdb.workbench.cors.enable=true
        -Dgraphdb.connector.port=7200
        -Dhttp.proxyHost=localhost|127.*|[::1]
        -Dhttp.proxyPort=7480
        -Denable-context-index=true
        -Dentity-pool-implementation=transactional
        -Dhealth.max.query.time.seconds=60
        -Dgraphdb.append.request.id.headers=true
        -Dreuse.vars.in.subselects=true
    ports:
      - "7200:7200"
    volumes:
      - ${GRAPHDB_HOME}:/opt/graphdb/home
      - ./src/test/resources/graphdb-docker-master/free-edition/LICENSE.txt:/opt/graphdb/dist/LICENSE.txt
  proxy:
    container_name: graphdbproxy
    build:
      context: ./
      dockerfile: Dockerfile
    image: starversproxy:latest
    network_mode: host # Funktioniert ab docker-compose 1.25 nicht mehr
    restart: unless-stopped
    ports:
      - "7480:7480"
    entrypoint: ['java', '-jar', '/opt/proxy/target/StarVersProxy-1.0-SNAPSHOT-jar-with-dependencies.jar']




